[package]
name = "proxyplz"
version = "0.1.0"
edition = "2021"

[dependencies]
warp = "0.3"
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1", features = ["full"] }
bytes = "1.10.0"
thiserror = "2.0.11"
